Repository Sofiav014/ISIS3510-Team32-Flutter, pull requests merged in 2025-05, with the labels that each got.

#75 Feat/record screen time
  lib/core/go_router.dart
  lib/core/screen_time.service.dart
  lib/views/create_booking_view.dart
  lib/views/initiation_view.dart
Labels: enhancement

#77 Feat/join booking
  lib/core/go_router.dart
  lib/core/screen_time_service.dart
  lib/models/repositories/booking_repository.dart
  lib/models/repositories/venue_repository.dart
  lib/view_models/venue_detail/venue_detail_bloc.dart
  lib/view_models/venue_detail/venue_detail_state.dart
  lib/views/create_booking_view.dart
  lib/views/initiation_view.dart
  lib/views/venue_detail_view.dart
  lib/widgets/home_view/recommended_booking_card_widget.dart
  lib/widgets/venue_detail_widgets/booking_info_card.dart
Labels: enhancement

#81 Fix/eventual connectivity home view
  lib/constants/errors.dart
  lib/widgets/home_view/recommended_booking_card_widget.dart
  lib/widgets/venue_detail_widgets/booking_info_card.dart
Labels: fix

#82 Feat/join booking isolate
  lib/constants/sports.dart
  lib/models/data_models/user_model.dart
  lib/models/repositories/booking_repository.dart
  lib/view_models/create_booking/create_booking_bloc.dart
  lib/widgets/home_view/recommended_booking_card_widget.dart
  lib/widgets/venue_detail_widgets/booking_info_card.dart
Labels: enhancement

#79 Feature: BQ #3
  lib/core/go_router.dart
  lib/core/loading_time_service.dart
  lib/core/service_locator.dart
  lib/core/theme_frecuency_service.dart
  lib/main.dart
  lib/models/repositories/auth_repository.dart
  lib/models/repositories/home_repository.dart
  lib/view_models/theme/theme_bloc.dart
  lib/views/initiation_view.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
Labels: analytics, fix

#89 feat: implement caching for booking state
  lib/view_models/create_booking/create_booking_bloc.dart
  lib/view_models/create_booking/create_booking_state.dart
  lib/view_models/theme/theme_bloc.dart
  lib/widgets/create_booking_view/time_slot_selector_widget.dart
Labels: enhancement

#96 refactor: validate booking fields before checking connectivity status
  lib/views/create_booking_view.dart
Labels: refactor

#95 Feat/90 hive update cache when joining or creating booking
  .vscode/launch.json
  lib/models/repositories/booking_repository.dart
  lib/view_models/create_booking/create_booking_bloc.dart
Labels: enhancement

#98 feat: add event to overwrite time slot in booking process
  lib/view_models/create_booking/create_booking_bloc.dart
  lib/view_models/create_booking/create_booking_event.dart
  lib/widgets/create_booking_view/time_slot_selector_widget.dart
Labels: fix

#99 fix: Join Booking isolate in venue detail view
  lib/models/repositories/home_repository.dart
  lib/models/repositories/venue_repository.dart
  lib/view_models/venue_detail/venue_detail_bloc.dart
  lib/view_models/venue_detail/venue_detail_event.dart
  lib/views/venue_detail_view.dart
  lib/widgets/venue_detail_widgets/booking_info_card.dart
Labels: fix

#101 Feat: Add booking detail (Join and Cancel booking feature included)
  lib/core/go_router.dart
  lib/models/repositories/booking_repository.dart
  lib/models/repositories/home_repository.dart
  lib/view_models/booking_detail/booking_detail_bloc.dart
  lib/view_models/booking_detail/booking_detail_event.dart
  lib/view_models/booking_detail/booking_detail_state.dart
  lib/views/booking_detail_view.dart
  lib/views/create_booking_view.dart
  lib/views/home_view.dart
  lib/views/profile_view.dart
  lib/views/search_view.dart
  lib/views/venue_detail_view.dart
  lib/views/venue_list_view.dart
  lib/widgets/booking_detail_view/booking_info_widget.dart
  lib/widgets/booking_detail_view/venue_detail_image_widget.dart
  lib/widgets/create_booking_view/time_slot_selector_widget.dart
  lib/widgets/home_view/recommended_booking_card_widget.dart
  lib/widgets/home_view/sport_popularity_report_widget.dart
  lib/widgets/home_view/upcoming_booking_card_widget.dart
  lib/widgets/home_view/venue_popularity_report_widget.dart
  lib/widgets/initiation_view/icon_selection_button_widget.dart
  lib/widgets/initiation_view/initiation_icon_toggle_button_widget.dart
  lib/widgets/login_view/google_sign_in_widget.dart
  lib/widgets/navbar/bottom_navigation_widget.dart
  lib/widgets/search_view/sport_button_widget.dart
  lib/widgets/search_view/venue_list_widget.dart
  lib/widgets/search_view_widgets/venue_list_widget.dart
  lib/widgets/venue_detail_widgets/booking_info_card.dart
  lib/widgets/venue_detail_widgets/venue_detail_image_widget.dart
Labels: enhancement

#105 Feat/buisness question time interaction
  lib/core/interaction_time_service.dart
  lib/main.dart
  lib/views/profile_view.dart
Labels: analytics

#106 feat: update timeInteractionStats to handle connectivity state and log interactions on app lifecycle events
  lib/core/interaction_time_service.dart
  lib/main.dart
Labels: enhancement

#107 Add Loading Time Service to Venue List View
  lib/views/venue_list_view.dart
Labels: analytics
