Repository Sofiav014/ISIS3510-Team32-Flutter, pull requests merged in 2025-04, with the labels that each got.

#29 fix: search view scrollable
  lib/views/search_view.dart
Labels: fix

#27 fix: search view pixel overflow
  lib/widgets/search_view_widgets/sport_button_widget.dart
Labels: fix

#30 Fix: Initiation responsiveness and interactions
  lib/views/initiation_view.dart
  lib/views/login_view.dart
  lib/widgets/initiation_icon_toggle_button_widget.dart
Labels: fix

#32 Fix/pixel overflow
  lib/view_models/venue_list/venue_list_bloc.dart
  lib/widgets/google_sign_in_widget.dart
  lib/widgets/venue_popularity_report_widget.dart
Labels: fix

#34 Fix: Input not setting value properly
  lib/views/initiation_view.dart
Labels: bug

#36 feat: display user-to-venue distance in Venue List
  lib/models/venue_model.dart
  lib/view_models/venue_list/venue_list_bloc.dart
  lib/widgets/search_view_widgets/venue_list_widget.dart
Labels: enhancement

#38 refactor(crashlytics): include current view info using setCustomKey
  lib/main.dart
  lib/views/home_view.dart
  lib/views/initiation_view.dart
  lib/views/login_view.dart
  lib/views/profile_view.dart
  lib/views/search_view.dart
  lib/views/venue_list_view.dart
Labels: enhancement, analytics

#40 39 fix/add rating to popularity report
  lib/repositories/home_repository.dart
  lib/views/home_view.dart
  lib/widgets/sport_popularity_report_widget.dart
  lib/widgets/venue_popularity_report_widget.dart
Labels: fix

#41 feat: enhance error handling, venue distance display, initiation flow and popularity metrics
  lib/main.dart
  lib/models/venue_model.dart
  lib/repositories/home_repository.dart
  lib/view_models/venue_list/venue_list_bloc.dart
  lib/views/home_view.dart
  lib/views/initiation_view.dart
  lib/views/login_view.dart
  lib/views/profile_view.dart
  lib/views/search_view.dart
  lib/views/venue_list_view.dart
  lib/widgets/google_sign_in_widget.dart
  lib/widgets/initiation_icon_toggle_button_widget.dart
  lib/widgets/search_view_widgets/sport_button_widget.dart
  lib/widgets/search_view_widgets/venue_list_widget.dart
  lib/widgets/sport_popularity_report_widget.dart
  lib/widgets/venue_popularity_report_widget.dart
Labels: enhancement, fix

#55 feat: enhance venue popularity report with subtitles for better context
  lib/views/home_view.dart
  lib/widgets/bottom_navigation_widget.dart
  lib/widgets/venue_popularity_report_widget.dart
Labels: enhancement

#59 feat/49-venue-detail-view
  assets/icons/heart_add.svg
  lib/core/app_colors.dart
  lib/core/go_router.dart
  lib/models/repositories/venue_repository.dart
  lib/view_models/venue_detail/venue_detail_bloc.dart
  lib/view_models/venue_detail/venue_detail_event.dart
  lib/view_models/venue_detail/venue_detail_state.dart
  lib/views/venue_detail_view.dart
  lib/widgets/search_view_widgets/venue_list_widget.dart
  lib/widgets/venue_detail_widgets/booking_info_card.dart
  lib/widgets/venue_detail_widgets/venue_detail_image_widget.dart
Labels: enhancement

#58 Feat/44 eventual connectivity home view
  lib/constants/errors.dart
  lib/core/service_locator.dart
  lib/models/data_models/booking_model.dart
  lib/models/data_models/venue_model.dart
  lib/models/hive/booking_model_hive.dart
  lib/models/hive/booking_model_hive.g.dart
  lib/models/hive/sport_model_hive.dart
  lib/models/hive/sport_model_hive.g.dart
  lib/models/hive/venue_model_hive.dart
  lib/models/hive/venue_model_hive.g.dart
  lib/models/repositories/home_repository.dart
  lib/view_models/connectivity/connectivity_bloc.dart
  lib/view_models/home/home_bloc.dart
  lib/view_models/home/home_state.dart
  lib/views/home_view.dart
  pubspec.yaml
Labels: enhancement

#62 feat: Eventual Connectivity Create Booking View
  lib/constants/errors.dart
  lib/models/repositories/booking_repository.dart
  lib/view_models/create_booking/create_booking_bloc.dart
  lib/views/create_booking_view.dart
  lib/widgets/create_booking_view/date_picker_widget.dart
  lib/widgets/create_booking_view/time_slot_selector_widget.dart
Labels: enhancement

#66 Feat/50 eventual connectivity search view
  lib/core/app_colors.dart
  lib/models/repositories/venue_repository.dart
  lib/view_models/home/home_bloc.dart
  lib/view_models/venue_detail/venue_detail_bloc.dart
  lib/view_models/venue_detail/venue_detail_state.dart
  lib/view_models/venue_list/venue_list_bloc.dart
  lib/view_models/venue_list/venue_list_state.dart
  lib/views/venue_detail_view.dart
  lib/views/venue_list_view.dart
  lib/widgets/home_view/upcoming_booking_card_widget.dart
  lib/widgets/search_view/venue_list_widget.dart
  lib/widgets/venue_detail_widgets/venue_detail_image_widget.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
Labels: enhancement

#67 Feature: Added Eventual Connectivity to Initialization
  lib/views/initiation_view.dart
  lib/views/profile_view.dart
  lib/widgets/login_view/google_sign_in_widget.dart
Labels: enhancement

#68 fix: adjust width in ProfileCardTextWidget and update AppBar text col…
  lib/views/profile_view.dart
  lib/views/venue_list_view.dart
Labels: fix

#71 fix image caching profile view
  lib/widgets/search_view_widgets/venue_list_widget.dart
Labels: fix

#73 fix: home view connectivity error
  lib/models/repositories/home_repository.dart
  lib/views/home_view.dart
  lib/views/profile_view.dart
  lib/views/venue_detail_view.dart
  lib/widgets/create_booking_view/date_picker_widget.dart
  lib/widgets/create_booking_view/time_slot_selector_widget.dart
  lib/widgets/home_view/upcoming_booking_card_widget.dart
Labels: fix
